# Generated by Django 2.2.17 on 2022-07-25 02:09

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_picture', '0011_auto_20190314_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='caption_text',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Provide a description, attribution, copyright or other information.', null=True, verbose_name='Caption text'),
        ),
    ]
